Major updates 'n stuff
sciwhiz12/sciwhiz12.github.io pull request #27
Opened 2021-04-29 16:27 UTC by TheCurle

So yeah. A lot happened recently.

2021-04-29 20:39 UTC, ravenbuilder934 approved these changes

2021-05-02 21:38 UTC, SizableShrimp commented
My username is SizableShrimp, not Siz**e**ableShrimp as used in the quote data.

2021-05-02 21:56 UTC, ravenbuilder934 commented
Needs the latest quotes!

2021-05-02 21:59 UTC, TheCurle commented
You needs the latest stabbies!

2021-05-02 22:00 UTC, ravenbuilder934 commented
Okay fine, but *also* the latest quotes!

2021-05-03 06:17 UTC, sciwhiz12 requested changes
Needs more changes before we can :shipit:

2021-05-03 06:17 UTC, sciwhiz12 commented on quotes/data.json
>          },
`superhelper` is above `collaborator`, according to the roles list (as viewed through Discord Mobile).

2021-05-03 06:17 UTC, sciwhiz12 commented on quotes/data.json
> +        },
`retrogradle` is below `contributor`, according to the roles list (as viewed through Discord Mobile).

2021-05-03 06:17 UTC, sciwhiz12 commented on quotes/data.json
> +            "text": "<tt>pmm</tt> Porn Mod Manager"
```suggestion
            "text": "<code>pmm</code> Porn Mod Manager <code>/S</code>"
```

2021-05-03 06:17 UTC, sciwhiz12 commented on quotes/data.json
> +            "text": "then you realise the truth [...] there is no spoon."
```suggestion
            "text": "then you realise the truth <p>there is no spoon.</p>"
```

2021-05-06 20:59 UTC, TheCurle commented
Superhelper above Collaborator, Retrogradle below Contributor.
tt -> code, [..] -> <p>

I'll poke the newest quotes in a few minutes. The mobile interface is such a gigantic pain in the repository.

2021-05-07 19:46 UTC, FinnT730 commented
> I'll poke the newest quotes in a few minutes.

It's been a full day, dear

2021-05-07 19:51 UTC, ravenbuilder934 commented
*23 hours

2021-05-07 21:09 UTC, FinnT730 commented
> *23 hours

You lying bird! /S
![image](https://user-images.githubusercontent.com/7442674/117508620-346ef780-af89-11eb-9ef0-c46735d17b7f.png)

2021-05-07 21:12 UTC, ravenbuilder934 commented
Github *rounds* you see
You must take a left at the Wendy's, go down Main, and hover over the "yesterday"

2021-05-10 16:31 UTC, TheCurle commented
THERE.
IT'S DONE.
ARE YOU HAPPY NOW?

2021-05-10 16:41 UTC, ravenbuilder934 commented on quotes/data.json
> +            "text": "rm -f /bee/illy"
tsk tsk, where's the null for 404?

2021-05-10 16:42 UTC, TheCurle commented on quotes/data.json
> +            "text": "The real hell was in us all along [...] That or i just set fire to everything again"
?

2021-05-10 16:42 UTC, TheCurle commented on quotes/data.json
> +            "text": "Those insane people also live in the funny farm [...] The Funny Farm, where life is beautiful all the time, and I'll be happy to see those nice young men in their clean white coa
?

2021-05-10 16:42 UTC, TheCurle commented on quotes/data.json
> +            "text": "rm -f /bee/illy"
Whoops, didn't see that

2021-05-10 16:56 UTC, ravenbuilder934 commented on quotes/data.json
> +            "text": "Those insane people also live in the funny farm [...] The Funny Farm, where life is beautiful all the time, and I'll be happy to see those nice young men in their clean white coa
pppp. P p p p p

2021-05-10 17:11 UTC, TheCurle commented
SHIP ITTTTT

2021-05-10 17:17 UTC, merged

2021-05-12 15:05 UTC, FinnT730 commented
\O/