quotes: upto 651
sciwhiz12/sciwhiz12.github.io pull request #31
Opened 2021-07-15 17:22 UTC by AterAnimAvis

- [ ] quote 629 spoiler css
- [ ] validate user information again

I've got some cleanup / improvements that I'll continue working on before pr'ing seperately

2021-07-20 18:42 UTC, ravenbuilder934 commented on quotes/data.json
> +            "text": " he's posting awful curle mechatrons with massive eggplant dicks"
space?

2021-07-20 18:42 UTC, ravenbuilder934 commented on quotes/data.json
> +            "text": " the (Party Escort™️ Submission Position™️)™️"
space?

2021-07-20 19:51 UTC, AterAnimAvis commented
Only thing left to do here is the NSFW boolean

2021-07-20 20:51 UTC, ravenbuilder934 requested changes
NSFW boolean stuff. if I was on the fence I tried to mark it as nsfw (but with a question mark). some existing ones may need nsfw markings as well:
 - 7
 - 42(?)
 - 68(?)
 - 76
 - 77(?)
 - 81(?)
 - 91
 - 124(?)
 - 164(?)
 - 177(?)
 - 181(?)
 - 195(?)
 - 208, 210, 211?
 - 221(?)
 - Remove 226, maybe
 - 235
 - 238, 239(?)
 - 240
 - 245, 249(?)
 - 269(?)
 - 273(?)
 - 274
 - 299
 - 300(?)
 - 323(?)
 - 331
 - 348
 - 356
 - 380(?)
 - 385(?)
 - 399(?)
 - 407(?)
 - 451(?)
 - 457
 - 458
 - 459
 - 467(?)
 - 468(?)
 - 476(?)
 - 480
 - 499(?)
 - 515
 - 536(?)
 - 541(?)
 - 542(?)
 - 562(?)

2021-07-20 20:51 UTC, ravenbuilder934 commented on quotes/data.json
> +            "text": "im going to fuck windows completely now"
nsfw?

2021-07-20 20:51 UTC, ravenbuilder934 commented on quotes/data.json
> +            "text": ":cummies: [...] :yummies:"
nsfw.

2021-07-20 20:51 UTC, ravenbuilder934 commented on quotes/data.json
> +            "text": "he's posting awful curle mechatrons with massive eggplant dicks"
nsfw

2021-07-20 20:51 UTC, ravenbuilder934 commented on quotes/data.json
> +            "text": "Aperture can suck my quantum tunneling cock"
nsfw

2021-07-20 20:51 UTC, ravenbuilder934 commented on quotes/data.json
> +            "text": "Fellate me"
nsfw

2021-07-20 20:51 UTC, ravenbuilder934 commented on quotes/data.json
> +            "text": "It’s only the first CUM, its not boring "
nsfw

2021-07-20 20:51 UTC, ravenbuilder934 commented on quotes/data.json
> +            "text": "beat it with a dick until it works"
nsfw?

2021-07-20 20:51 UTC, ravenbuilder934 commented on quotes/data.json
> +            "text": "Yes I'm f***in asher"
nsfw.

2021-07-20 20:51 UTC, ravenbuilder934 commented on quotes/data.json
> +            "text": "have you tried replacing tit?"
nsfw?

2021-07-20 20:51 UTC, ravenbuilder934 commented on quotes/data.json
> +            "text": "here's my cum [...] it's thicc"
nsfw.

2021-07-20 20:51 UTC, ravenbuilder934 commented on quotes/data.json
> +            "text": "juicy [...] it is stringy.... [...] now it is in my face"
nsfw?

2021-07-20 20:51 UTC, ravenbuilder934 commented on quotes/data.json
> +            "text": "Yes ashers, a can of peas costs 40 penises"
nsfw

2021-07-20 20:51 UTC, ravenbuilder934 commented on quotes/data.json
> +            "text": "SIX HUNDRED PENISES"
nsfw

2021-07-20 20:51 UTC, ravenbuilder934 commented on quotes/data.json
> +            "text": "Penis?"
nsfw

2021-07-20 20:51 UTC, ravenbuilder934 commented on quotes/data.json
> +            "text": "Oh, you like other people imagining you and penises?"
nsfw

2021-07-20 20:51 UTC, ravenbuilder934 commented on quotes/data.json
> +            "text": "lies, its a gigantic cock"
nsfw

2021-07-20 20:51 UTC, ravenbuilder934 commented on quotes/data.json
> +            "text": "Unbe is too deep"
nsfw

2021-07-20 20:51 UTC, ravenbuilder934 commented on quotes/data.json
> +            "text": "the more they bounce around the lewder they get"
nsfw?

2021-07-20 20:51 UTC, ravenbuilder934 commented on quotes/data.json
> +            "text": "any hole's a goal"
nsfw?

2021-07-20 20:51 UTC, ravenbuilder934 commented on quotes/data.json
> +            "text": "lol president for porn"
nsfw

2021-07-20 20:51 UTC, ravenbuilder934 commented on quotes/data.json
> +            "text": "reject humanity, return to mnke"
..typo?

2021-07-20 20:51 UTC, ravenbuilder934 commented on quotes/data.json
> +            "text": "All current IDEs suck, we need a new one.. with blackjack.. and hookers..."
nsfw?

2021-07-20 20:51 UTC, ravenbuilder934 commented on quotes/data.json
> +            "text": "You're not wrong but we don't need to talk about curle's asshole"
nsfw?

2021-07-20 20:51 UTC, ravenbuilder934 commented on quotes/data.json
> +            "text": "oh god has illy been fucking his cat again"
nsfw.

2021-07-20 20:51 UTC, ravenbuilder934 commented on quotes/data.json
> +            "text": "Raven is octopussy confirmed"
nsfw?

2021-07-20 20:51 UTC, ravenbuilder934 commented on quotes/data.json
> +            "text": "Seduce me"
nsfw?

2021-07-20 20:51 UTC, ravenbuilder934 commented on quotes/data.json
> +            "text": "<span class=\"spoiler\">Incest in a Private localized livingroom son™ (only 5 small payments of 59.999.999,99)</span>"
REALLY fucking nsfw

2021-07-20 20:51 UTC, ravenbuilder934 commented on quotes/data.json
> +            "text": "Butt, Butt [...] Big Big Praise [...] It's fucking hard"
nsfw?

2021-07-20 20:51 UTC, ravenbuilder934 commented on quotes/data.json
> +            "text": "were squirrel fucks are given to each of us"
nsfw?

2021-07-20 20:51 UTC, ravenbuilder934 commented on quotes/data.json
> +            "text": "curle can go very deep when she wants to"
nsfw?

2021-07-20 20:51 UTC, ravenbuilder934 commented on quotes/data.json
> +            "text": "You fucked and then saw it coming?"
nsfw.

2021-07-20 20:51 UTC, ravenbuilder934 commented on quotes/data.json
> +            "text": "yarrrrr ya never saw it cummin'"
nsfw.

2021-07-20 20:51 UTC, ravenbuilder934 commented on quotes/data.json
> +            "text": "how dare you fuck someone and see them at the same time"
nsfw.

2021-07-20 20:51 UTC, ravenbuilder934 commented on quotes/data.json
> +            "text": "illy is cpw's sub now?"
nsfw?

2021-07-20 20:51 UTC, ravenbuilder934 commented on quotes/data.json
> +            "text": "I'll grab the lube"
nsfw?

2021-07-20 20:51 UTC, ravenbuilder934 commented on quotes/data.json
> +            "text": "ah yes [..] fellation [..] the classic family activity"
nsfw.

2021-07-20 20:51 UTC, ravenbuilder934 commented on quotes/data.json
> +            "text": "You have to admit its a nice rack"
nsfw, maybe?

2021-07-20 20:51 UTC, ravenbuilder934 commented on quotes/data.json
> +            "text": "massive rack and a butt big enough to have its own phone number"
nsfw, maybe? prolly not but *shrugs*

2021-07-20 20:51 UTC, ravenbuilder934 commented on quotes/data.json
> +            "text": "Calculus makes finn hard?"
nsfw?

2021-07-20 20:51 UTC, ravenbuilder934 commented on quotes/data.json
> +            "text": "finn's sex dungeon"
nsfw.

2021-07-20 20:51 UTC, ravenbuilder934 commented on quotes/data.json
> +            "text": "boy ass juicy"
nsfw?

2021-07-20 20:51 UTC, ravenbuilder934 commented on quotes/data.json
> +            "text": "purity = cock??"
nsfw?

2021-07-20 20:51 UTC, ravenbuilder934 commented on quotes/data.json
> +            "text": "get. fucked. raven"
nsfw?

2021-07-20 20:51 UTC, ravenbuilder934 commented on quotes/data.json
> +            "text": "By popular demand, Forge has grown a CoC!"
nsfw?

2021-07-20 20:51 UTC, ravenbuilder934 commented on quotes/data.json
> +            "text": "WHERE'S THE DICK"
nsfw?

2021-07-21 18:55 UTC, ravenbuilder934 approved these changes

2021-07-27 12:39 UTC, sciwhiz12 approved these changes
It is time. _(and i just remembered about this)_
:shipit:

2021-07-27 12:39 UTC, merged